- hosts: controller
  tasks:
    - name: run packstack with pre created answer file
      command: /bin/sh /vagrant/packstack/execute_packstack.sh -a
      register: output
      become: true
      become_user: root
      become_method: sudo
    # - debug: var=item.stdout
      # with_items: output.results