- hosts: controller
  tasks:
    - name: ensure SSH key is generated
      command: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
      args:
        creates: /root/.ssh/id_rsa
      become: true

    - name: retrieve public key
      shell: cat /root/.ssh/id_rsa.pub
      register: master_public_key
      changed_when: false
      become: true

- hosts: all
  tasks:
    - name: add master public key to all nodes
      authorized_key:
        user: root
        key: "{{ hostvars['controller'].master_public_key.stdout }}"
      become: true