# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagranfile to provide 3 boxes for Openstack deployment (openstack, and 2 compute nodes)
# Create 2 host only network, and use IP address from the auto generated subnet to replace 
# the existing one

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant"

  # config.vm.define "controller" do |controller|
  #   controller.vm.box = "centos/7"
  #   controller.vm.hostname = "controller"
  #   controller.vm.network "private_network", ip: "192.168.3.10"
  #   controller.vm.network "private_network", ip: "192.168.80.10"
  #   controller.vm.provider "vmware_fusion" do |v|
  #     v.vmx["memsize"] = "8192"
  #     v.vmx["numvcpus"] = "8"
  #     v.vmx["vhv.enable"] = "TRUE"
  #     # v.vmx["ethernet0.pciSlotNumber"] = "33"
  #   end
  #   controller.vm.provision :ansible_local do |ansible|
  #     ansible.playbook       = "config_allin.yaml"
  #     # ansible.verbose        = true
  #     ansible.install        = true
  #     ansible.limit          = "all" # or only "nodes" group, etc.
  #     ansible.inventory_path = "hosts_allin"
  #   end
  # end

    config.vm.define "controller" do |controller|
    controller.vm.box = "centos/7"
    controller.vm.hostname = "controller"
    controller.vm.network "private_network", ip: "192.168.33.10"
    controller.vm.network "private_network", ip: "192.168.133.10"
    controller.vm.provider "virtualbox" do |v|
      v.name = "controller"
      v.cpus = 8
      v.memory = 8192
    end 
    controller.vm.provision :ansible_local do |ansible|
      ansible.playbook       = "config_allin.yaml"
      # ansible.verbose        = true
      ansible.install        = true
      ansible.limit          = "all" # or only "nodes" group, etc.
      ansible.inventory_path = "hosts_allin"
    end
  end
end
